/*==============================================================================================

    sandbox/engine/sb_res/sb_res.c -- Test sandbox for the engine/res resource catalogue.

    Proves the properties the rest of the design leans on:
      - identity:      the same name yields the same rid_t from any site, with or without
                       the registry; canonical folding makes case and slash direction moot
      - idempotency:   re-registering a name (a hot-reload swap) changes nothing
      - ownership:     a name registered from a buffer that is then overwritten reads back
                       intact, because the pool copies
      - collisions:    two names arriving under one id are refused and both are reported
      - misses:        an unknown or invalid id is a clean NULL/false, never a crash
      - mod lifecycle: a module descriptor carrying a res_table gets registered by the
                       pre_init hook when mod_init_all runs, and again on re-registration
                       without growing the catalogue
      - harvest:       this executable's own table, generated by the build from the RID()
                       literals in this file, arrives through res's descriptor with no
                       hand-written registration -- the build-time half of the design

    Exit code is the number of failed checks, so it can gate a build step.

==============================================================================================*/

#include <stdio.h>
#include <string.h>

#include "orb.h"
#include "engine/mod/mod_host.h"
#include "engine/sys/sys_host.h"
#include "engine/res/res_host.h"

/*==============================================================================================
    Check helper
==============================================================================================*/

static int s_checks = 0;
static int s_fails  = 0;

static void
sb_check( bool ok, const char* what )
{
    s_checks++;
    if ( !ok )
    {
        s_fails++;
        printf( "    FAIL: %s\n", what );
    }
}

/* Visitor for res_each: counts the entries it is handed. */
static void
count_visitor( rid_t id, const char* name, void* user )
{
    UNUSED( id );
    UNUSED( name );
    ( *( u32* )user )++;
}

/*==============================================================================================
    Identity
==============================================================================================*/

static void
test_identity( void )
{
    printf( "  identity\n" );
    res_init();

    /* Two sites spelling the same literal agree without touching the registry. */
    rid_t a = RID( "ui/icon/save" );
    rid_t b = RID( "ui/icon/save" );
    sb_check( a == b, "same literal -> same id" );
    sb_check( a != RID_INVALID, "id is never RID_INVALID" );
    sb_check( a != RID( "ui/icon/load" ), "different names -> different ids" );

    /* Canonical form: case and separator direction are not identity.  A trailing slash IS:
       it names the subtree, a different resource from the leaf, and RES_TREE() is the door
       that appends it.  An author-written trailing slash is a build error, so the two
       spellings are compared through the hash directly. */
    sb_check( RID( "UI/Icon/Save" ) == a, "case folds" );
    sb_check( RID( "ui\\icon\\save" ) == a, "backslash folds to slash" );
    sb_check( RES_TREE( "ui/icon" ) == res_hash_name( "ui/icon/" ),
              "RES_TREE names the subtree with its slash" );
    sb_check( RES_TREE( "ui/icon" ) != res_hash_name( "ui/icon" ),
              "a subtree and its leaf are different ids" );

    /* Registration returns the same id the macro computes, and the stored name is canonical. */
    rid_t r = res_register( "UI\\Icon\\Save" );
    sb_check( r == a, "register returns the hashed id" );
    sb_check( res_exists( a ), "registered id exists" );
    sb_check( res_name( a ) && strcmp( res_name( a ), "ui/icon/save" ) == 0,
              "name reads back canonical" );
    sb_check( res_count() == 1, "one entry" );

    char canon[ 64 ];
    u32  len = res_canon( "Font/Cascadia_Mono\\16", canon, sizeof( canon ) );
    sb_check( len == 21 && strcmp( canon, "font/cascadia_mono/16" ) == 0, "res_canon folds in place" );
    sb_check( res_canon( "abc", canon, 3 ) == 0, "res_canon rejects a name that does not fit" );
}

/*==============================================================================================
    Idempotency (hot-reload shape)
==============================================================================================*/

static void
test_idempotent( void )
{
    printf( "  idempotency\n" );
    res_init();

    rid_t first = res_register( "font/cascadia_mono/16" );
    u32   n     = res_count();

    /* A reloaded DLL registers its table again: same ids, no growth. */
    for ( int i = 0; i < 3; ++i )
    {
        rid_t again = res_register( "font/cascadia_mono/16" );
        sb_check( again == first, "re-register returns the same id" );
    }
    sb_check( res_count() == n, "re-register does not grow the catalogue" );

    /* An id taken before the swap still resolves after it. */
    rid_t held = RID( "font/cascadia_mono/16" );
    sb_check( res_name( held ) != NULL, "id held across re-registration still resolves" );
}

/*==============================================================================================
    Ownership (pool copies)
==============================================================================================*/

static void
test_pool_copies( void )
{
    printf( "  ownership\n" );
    res_init();

    char buf[ 64 ];
    strcpy( buf, "shader/gui_quad" );
    rid_t id = res_register( buf );

    /* Simulate the referencing image going away: scribble the source buffer. */
    memset( buf, 'X', sizeof( buf ) - 1 );
    buf[ sizeof( buf ) - 1 ] = 0;

    const char* name         = res_name( id );
    sb_check( name != NULL, "name survives source buffer death" );
    sb_check( name && strcmp( name, "shader/gui_quad" ) == 0,
              "name text is the original, not the scribble" );
    sb_check( name != buf, "name pointer is not the caller's buffer" );
}

/*==============================================================================================
    Growth

    Storage starts unallocated and doubles as it fills.  A rehash rebuilds every bucket and a
    pool realloc moves the name text, so the property that matters is that an id registered
    before a growth still resolves afterwards, and to the name it was given.
==============================================================================================*/

#define SB_GROWTH_NAMES 5000
#define SB_GROWTH_FMT   "growth/level_%04u/mesh"

static void
test_growth( void )
{
    printf( "  growth\n" );
    res_init();

    sb_check( res_count() == 0, "catalogue is empty before the first registration" );

    /* Several doublings past both RES_INIT_ENTRIES and RES_INIT_POOL. */
    static rid_t ids[ SB_GROWTH_NAMES ];
    char         name[ 64 ];
    u32          registered = 0;

    for ( u32 i = 0; i < SB_GROWTH_NAMES; ++i )
    {
        snprintf( name, sizeof( name ), SB_GROWTH_FMT, i );
        ids[ i ] = res_register( name );
        if ( ids[ i ] != RID_INVALID )
            registered++;
    }
    sb_check( registered == SB_GROWTH_NAMES, "every name registered" );
    sb_check( res_count() == SB_GROWTH_NAMES, "no name was dropped or folded into another" );

    /* Read the whole set back: the rehash reinserted every slot, and pool offsets still
       address the right text after the block moved underneath them. */
    u32 intact = 0;
    for ( u32 i = 0; i < SB_GROWTH_NAMES; ++i )
    {
        snprintf( name, sizeof( name ), SB_GROWTH_FMT, i );
        const char* got = res_name( ids[ i ] );
        if ( got && strcmp( got, name ) == 0 )
            intact++;
    }
    sb_check( intact == SB_GROWTH_NAMES, "every name reads back intact after growth" );

    /* The first name registered has survived the most reallocs of any. */
    const char* oldest = res_name( ids[ 0 ] );
    sb_check( oldest && strcmp( oldest, "growth/level_0000/mesh" ) == 0,
              "the oldest name survives every growth" );

    /* Re-registration is still a no-op at scale, not a second copy of the set. */
    for ( u32 i = 0; i < SB_GROWTH_NAMES; ++i )
    {
        snprintf( name, sizeof( name ), SB_GROWTH_FMT, i );
        res_register( name );
    }
    sb_check( res_count() == SB_GROWTH_NAMES, "re-registering the grown set adds nothing" );

    u32 visited = 0;
    res_each( count_visitor, &visited );
    sb_check( visited == SB_GROWTH_NAMES, "res_each visits every entry once after growth" );

    /* res_init releases the storage and leaves a catalogue that still works. */
    res_init();
    sb_check( res_count() == 0, "res_init empties the catalogue" );
    sb_check( res_name( ids[ 0 ] ) == NULL, "an id from before the reset no longer resolves" );
    sb_check( res_register( "growth/after_reset" ) != RID_INVALID, "storage reallocates after a reset" );
}

/*==============================================================================================
    Collisions
==============================================================================================*/

static void
test_collision( void )
{
    printf( "  collisions\n" );
    res_init();

    /* Two real names on one FNV-1a 32 id, found by brute force.  The build-time scanner
       refuses this pair in source, so the runtime path can only be reached by hand. */
    rid_t id = res_hash_name( "collide/2ae/40b" );
    sb_check( id == res_hash_name( "collide/346/339" ), "the pair really collides" );

    rid_t r1 = res_register( "collide/2ae/40b" );
    rid_t r2 = res_register( "collide/346/339" );

    sb_check( r1 == id, "first registration under an id succeeds" );
    sb_check( r2 == RID_INVALID, "second name under the same id is refused" );
    sb_check( res_count() == 1, "the collision did not add an entry" );
    sb_check( res_name( id ) && strcmp( res_name( id ), "collide/2ae/40b" ) == 0,
              "first registration stands" );

    const char* err = res_last_error();
    sb_check( strstr( err, "collide/2ae/40b" ) != NULL, "error names the registered name" );
    sb_check( strstr( err, "collide/346/339" ) != NULL, "error names the rejected name" );
    sb_check( strstr( err, "collision" ) != NULL, "error says collision" );

    /* Same id, same name is not a collision. */
    rid_t r3 = res_register_id( id, "COLLIDE/2AE/40B" );
    sb_check( r3 == id, "same name under the same id is an idempotent hit" );

    /* A precomputed id must hash from its name; anything else came from a different hash
       and is refused before it can file the name where no RID() site will find it. */
    rid_t r4 = res_register_id( ( rid_t )0x01234567u, "level/alpha" );
    sb_check( r4 == RID_INVALID, "an id that does not hash from its name is refused" );
    sb_check( res_count() == 1, "the refused pair added nothing" );
    sb_check( strstr( res_last_error(), "does not hash" ) != NULL,
              "error says the id does not hash from the name" );
}

/*==============================================================================================
    Misses and bad input
==============================================================================================*/

static void
test_misses( void )
{
    printf( "  misses\n" );
    res_init();

    res_register( "ui/icon/save" );

    sb_check( res_name( RID( "ui/icon/never" ) ) == NULL, "unknown id -> NULL name" );
    sb_check( !res_exists( RID( "ui/icon/never" ) ), "unknown id -> not exists" );
    sb_check( res_name( RID_INVALID ) == NULL, "RID_INVALID -> NULL name" );
    sb_check( !res_exists( RID_INVALID ), "RID_INVALID -> not exists" );

    sb_check( res_register( "" ) == RID_INVALID, "empty name refused" );
    sb_check( res_register( NULL ) == RID_INVALID, "NULL name refused" );
    sb_check( res_register_id( RID_INVALID, "x" ) == RID_INVALID, "RID_INVALID as id refused" );

    char too_long[ RES_NAME_MAX + 2 ];
    memset( too_long, 'a', sizeof( too_long ) - 1 );
    too_long[ sizeof( too_long ) - 1 ] = 0;
    sb_check( res_register( too_long ) == RID_INVALID, "over-long name refused" );
    sb_check( res_count() == 1, "refused names add nothing" );
}

/*==============================================================================================
    Mod lifecycle: a descriptor's res_table registers through the pre_init hook

    A hand-built table on a fake module, the shape every DLL module's generated table
    takes.  Loading "res" also brings this executable's own generated table
    (g_host_res_table) along, so counts below are measured relative to that.
==============================================================================================*/

static const res_entry_t s_fake_entries[] = {
    { "fake/font/mono/16" },
    { "fake/icon/save" },
    { "fake/icon/load" },
    { "FAKE/ICON/SAVE" }, /* duplicate spelled differently: must not add an entry  */
};

static const res_table_t g_fake_res_table = {
    .entries = s_fake_entries,
    .count   = ARRAY_COUNT( s_fake_entries ),
};

/* The mod system requires a non-empty, fully populated api struct; one no-op suffices. */
typedef struct fake_api_s
{
    void ( *noop )( void );
} fake_api_t;

static void
fake_noop( void )
{}

static const fake_api_t g_fake_api_struct = { .noop = fake_noop };

static bool
fake_init( void* state, get_api_fn get_api )
{
    UNUSED( state );
    UNUSED( get_api );
    return true;
}

static mod_desc_t*
fake_get_mod_desc( void )
{
    static mod_desc_t desc = {
        .version       = 1,
        .state_size    = 0,
        .func_api_size = sizeof( fake_api_t ),
        .func_api      = &g_fake_api_struct,
        .deps          = { "res" },
        .dep_count     = 1,
        .init          = fake_init,
        .exit          = NULL,
        .reload        = NULL,
        .res_table     = MOD_RES_TABLE( fake ),
    };
    return &desc;
}

static void
test_mod_lifecycle( void )
{
    printf( "  mod lifecycle\n" );
    res_init();

    mod_system_init();
    res_wire_mod_callbacks();
    res_wire_mod_callbacks(); /* second wire is a no-op, not a double subscription */

    /* note: mod itself depends on sys */
    bool ok = mod_static_load( "sys", sys_get_mod_desc() ) &&
              mod_static_load( "res", res_get_mod_desc() ) &&
              mod_static_load( "fake", fake_get_mod_desc() );

    sb_check( ok, "static loads succeed" );
    sb_check( res_count() == 0, "load is passive: nothing registered before init_all" );

    ok = mod_init_all();
    sb_check( ok, "mod_init_all succeeds" );

    /* Both tables landed: the fake module's three distinct names, plus this exe's own.  The
       fake names are looked up through the hash directly, not RID(): they stand in for a
       DLL's names, which this executable's sources must not mention, or the build would
       harvest them into the host table and the two sets would no longer be disjoint. */
    u32 host_names = g_host_res_table.count;
    u32 n          = res_count();
    sb_check( n == host_names + 3,
              "pre_init registered the fake table (3 distinct names) and the host table" );
    sb_check( res_exists( res_hash_name( "fake/icon/load" ) ), "table name resolvable by id" );
    sb_check( res_name( res_hash_name( "fake/font/mono/16" ) ) != NULL, "font name present" );

    /* Hot-reload shape: the same table arrives again. */
    u32 again = res_register_table( &g_fake_res_table );
    sb_check( again == 4, "every table entry reports registered" );
    sb_check( res_count() == n, "re-registration did not grow the catalogue" );

    u32 visited = 0;
    res_each( count_visitor, &visited );
    sb_check( visited == n, "res_each visits each entry once" );

    /* Unloading the module leaves the catalogue intact: it is cumulative. */
    mod_system_exit();
    sb_check( res_count() == n, "catalogue survives module exit" );
    sb_check( res_name( res_hash_name( "fake/icon/save" ) ) != NULL, "names survive module exit" );
}

/*==============================================================================================
    Harvest: the build generated this executable's table from the RID() literals above

    Nothing in this file registers "ui/icon/never" by hand -- test_misses only ever asks
    for it -- yet the name is in g_host_res_table because res_tool found the literal.  That
    is the property the whole design rests on: what CAN be loaded is known at build time.
    The names the fake module registers are spelled only as plain strings in its table,
    never through RID(), so the harvest must NOT contain them.  The one RES_TREE() in
    test_identity arrives as "ui/icon/", slash included.
==============================================================================================*/

static void
test_harvest( void )
{
    printf( "  harvest\n" );
    res_init();

    sb_check( g_host_res_table.entries != NULL && g_host_res_table.count > 0,
              "the build generated a non-empty table for this exe" );

    /* Registering the generated table by hand behaves like any other table. */
    u32 registered = res_register_table( &g_host_res_table );
    sb_check( registered == g_host_res_table.count, "every generated entry registers" );
    sb_check( res_count() == g_host_res_table.count, "generated entries are distinct canonical names" );

    /* Subtree: harvested with its trailing slash, resolvable through RES_TREE(), and
       distinct from the leaf spelling, which nothing here names. */
    const char* tree = res_name( RES_TREE( "ui/icon" ) );
    sb_check( tree && strcmp( tree, "ui/icon/" ) == 0, "RES_TREE prefix harvested as a subtree name" );
    sb_check( !res_exists( res_hash_name( "ui/icon" ) ),
              "the leaf spelling of a subtree is not implied" );

    sb_check( res_exists( RID( "ui/icon/never" ) ), "a name only ever queried was still harvested" );
    sb_check( res_exists( RID( "ui/icon/save" ) ), "a name spelled in several cases harvested once" );
    sb_check( res_exists( RID( "font/cascadia_mono/16" ) ), "the held-id name was harvested" );
    sb_check( !res_exists( res_hash_name( "fake/icon/save" ) ),
              "plain-string names outside RID() are not harvested" );

    const char* canon = res_name( RID( "ui/icon/save" ) );
    sb_check( canon && strcmp( canon, "ui/icon/save" ) == 0, "generated names are canonical" );

    /* The table is exactly the set of RID() / RES_TREE() literals in this file: nothing
       extra rode in. */
    u32 expected = 0;
    for ( u32 i = 0; i < g_host_res_table.count; ++i )
    {
        const char* nm = g_host_res_table.entries[ i ].name;
        if ( strcmp( nm, "ui/icon/save" ) == 0 || strcmp( nm, "ui/icon/load" ) == 0 ||
             strcmp( nm, "ui/icon/never" ) == 0 || strcmp( nm, "font/cascadia_mono/16" ) == 0 ||
             strcmp( nm, "ui/icon/" ) == 0 )
            expected++;
    }
    sb_check( expected == g_host_res_table.count && expected == 5,
              "the generated table holds exactly the five names spelled through the doors in this file" );
}

/*==============================================================================================
    Entry
==============================================================================================*/

int
main( int argc, char** argv )
{
    UNUSED( argc );
    UNUSED( argv );

    printf( "sb_res: resource catalogue\n" );

    test_identity();
    test_idempotent();
    test_pool_copies();
    test_growth();
    test_collision();
    test_misses();
    test_mod_lifecycle();
    test_harvest();

    printf( "sb_res: %d checks, %d failed\n", s_checks, s_fails );
    return s_fails;
}

/*============================================================================================*/
