/*==============================================================================================

    runtime_service/gui/backend/gui_font_bmp.c -- bmp fonts: monospace R8 grid atlases.

    A "bmp font" is an 8-bit-per-pixel (R8) monospace grid atlas sampled at draw time.  The
    built-in fonts ship as 1-bit-per-pixel "bit fonts" (the generated font/*.c tables, described
    by bit_font_def_t); bmp_atlas_build() *expands* each bit font into a bmp atlas at init.  The
    same atlas could later be produced from an externally authored bmp source without being a
    compile-time built-in -- nothing here assumes the pixels came from a bit font once built.

    Atlas layout (bit font -> bmp, same formula for every built-in):
        16 glyphs per row x glyph_w pixels = atlas_w pixels wide
        N  glyph rows     x glyph_h pixels = atlas_h pixels tall
    Glyph index for character ch (32..127): idx = ch - 32; col = idx % 16, row = idx / 16.

    Every atlas is finalized by font_finalize_atlas() (gui_font.c): a white texel row plus the
    dash pattern rows are appended, and the white / dash / scale-free UV metrics are resolved.
    Only the scale-dependent metrics (char_h/line_h/char_w/size) are re-resolved per selection.

    Included by gui_backend.c after gui_font.h, before gui_font.c.

==============================================================================================*/
// clang-format off

/*==============================================================================================

    Font Tables (unity include data tables generated by font_tool)

    Good base design size (e.g., 8px, 12px, 16px, 24px, or 32px)
    https://www.dafont.com/bitmap.php

==============================================================================================*/

// GENERATED: bit font data (1-bpp glyph bitmaps and metadata) for 8x8-16x16 pixel glyphs
#include "runtime_service/gui/font/gen_8_16_data.c"

// F:\orb\font_source\JetBrainsMonoNL-Bold.ttf 16 jetbrains_bold_16.c
// F:\orb\font_source\JetBrainsMonoNL-Bold.ttf 20 jetbrains_bold_20.c
// F:\orb\font_source\JetBrainsMonoNL-Bold.ttf 24 jetbrains_bold_24.c
#include "runtime_service/gui/font/jetbrains_bold_16.c"
#include "runtime_service/gui/font/jetbrains_bold_20.c"
#include "runtime_service/gui/font/jetbrains_bold_24.c"

//  C:\WINDOWS\FONTS\CONSOLA.TTF 24 consola_24.c
#include "runtime_service/gui/font/consola_24.c"


/*----------------------------------------------------------------------------------------------
    bmp_font_t -- a bit font expanded into a resident runtime R8 atlas.
----------------------------------------------------------------------------------------------*/

typedef struct
{
    font_metrics_t              metrics;   // first: resolved metrics for this atlas
    const bit_font_def_t*       def;       // source bit font (grid + 1-bpp data)
    rhi_texture_t               atlas;     // GPU atlas
    u32                         atlas_idx; // bindless index
    u32                         tex_h;     // uploaded atlas height (atlas_h + white + dash rows)

} bmp_font_t;

/* One slot per gui_font_t; designated initializers keep slot == enum value, so bmp_select()
   and the init/shutdown loops can index directly. */
static bmp_font_t s_bmps[ GUI_FONT_BITMAP_MAX ] =
{
    // built-in fonts generated by AI
    [ GUI_FONT_BITMAP_8 ]           = { .def = &s_def_8 },
    [ GUI_FONT_BITMAP_16 ]          = { .def = &s_def_16 }, 

    // font_tool.exe generated
    [ GUI_FONT_BITMAP_16_JETBOLD]   = { .def = &s_def_jetbrains_bold_22 }, // fixed
    [ GUI_FONT_BITMAP_20_JETBOLD]   = { .def = &s_def_jetbrains_bold_27 }, // fixed
    [ GUI_FONT_BITMAP_24_JETBOLD ]  = { .def = &s_def_jetbrains_bold_33 }, // fixed

    [ GUI_FONT_BITMAP_24_CONSOLA ]  = { .def = &s_def_consola_24 },
};

static bmp_font_t*      s_bmp_active   = NULL;
static gui_font_t     s_bmp_font     = GUI_FONT_BITMAP_16;
static u32              s_bmp_scale    = 1;

static void
bmp_show_sizes( void )
{
    printf( "bmp fonts in memory (expanded from bit fonts):..\n" );
    for ( int i = 0; i < GUI_FONT_BITMAP_MAX; ++i )
    {
        const bit_font_def_t* def = s_bmps[ i ].def;
        printf( "%-32s: [%d] %-3dx%3d atlas, w:%2d h:%2d, %2d glyphs per row, row stride %2d\n",
            def->debug_name, i, def->atlas_w, def->atlas_h, def->glyph_w, def->glyph_h, def->glyphs_row, def->row_stride );
    }

    printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_8",          sizeof( s_font8_data ));
    printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_16",         sizeof( s_font16_data ));
    printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_12",         sizeof( s_font12_data ));
    // printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_16_PROGGY",  sizeof( s_font_proggy_tiny_16_data ));
    // printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_20_PROGGY",  sizeof( s_font_proggy_tiny_20_data ));
    printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_16_JETBOLD", sizeof( s_font_jetbrains_bold_22_data ));
    printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_20_JETBOLD", sizeof( s_font_jetbrains_bold_27_data  ));
    printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_24_JETBOLD", sizeof( s_font_jetbrains_bold_33_data  ));
    printf( "%-32s: %zu bytes\n", "GUI_FONT_BITMAP_24_CONSOLA", sizeof( s_font_consola_24_data  ));
    printf( "\n" );
}

/*----------------------------------------------------------------------------------------------
    Metrics resolution

    The scale-free metrics (white/dash UVs, inv_atlas_*) are set once by font_finalize_atlas at
    build time.  Only the scale-dependent fields are re-resolved here, on selection / scale change.
----------------------------------------------------------------------------------------------*/

static void
bmp_resolve_metrics( bmp_font_t* bf )
{
    const bit_font_def_t* def = bf->def;
    f32 s = (f32)s_bmp_scale;

    bf->metrics.char_h       = (f32)( def->glyph_h * s );
    bf->metrics.line_h       = (f32)( def->glyph_h + def->glyph_h / 4u ) * s;
    bf->metrics.char_w       = (f32)( def->glyph_w * s );
    bf->metrics.size         = (f32)( def->glyph_h * s );   // bmp em ~= the glyph cell height
    bf->metrics.atlas_idx    = bf->atlas_idx;
    bf->metrics.proportional = false;
}

void
bmp_select( gui_font_t font )
{
    /* Out-of-range requests fall back to the default 8x12 atlas. */
    if ( font >= GUI_FONT_BITMAP_MAX )
         font  = GUI_FONT_BITMAP_16;

    s_bmp_font     = font;
    s_bmp_active   = &s_bmps[ font ];
    bmp_resolve_metrics( s_bmp_active );
    /* The active-font pointer (s_font) is owned by the registry in gui_font.c; this routine
       only resolves the selected bmp's scale-dependent metrics. */
}

void
bmp_scale_set( u32 scale )
{
    s_bmp_scale = ( scale < 1u ) ? 1u : scale;
    if ( s_bmp_active )
        bmp_resolve_metrics( s_bmp_active );   // reapply scale-dependent metrics
}

/* Copy the active built-in bmp into a registry slot.  The slot references the resident atlas
   (owns_atlas == false), so freeing or reloading the slot never touches the built-in's GPU atlas. */
void
bmp_fill_slot( font_slot_t* slot )
{
    font_slot_free_gpu( slot );             // drop any owned atlas previously here

    slot->src        = FONT_SRC_BMP;
    slot->metrics    = s_bmp_active->metrics;   // metrics carry the bmp's atlas_idx
    slot->bmp.def    = s_bmp_active->def;
    slot->atlas      = ( rhi_texture_t ){ 0 };  // atlas owned by the resident built-in set
    slot->atlas_idx  = s_bmp_active->atlas_idx;
    slot->atlas_w    = s_bmp_active->def->atlas_w;
    slot->atlas_h    = s_bmp_active->tex_h;
    slot->owns_atlas = false;
    slot->used       = true;
}

/*----------------------------------------------------------------------------------------------
    bmp_atlas_destroy / bmp_atlas_build -- resident built-in atlas lifecycle.
----------------------------------------------------------------------------------------------*/

static void
bmp_atlas_destroy( bmp_font_t* bf )
{
    if ( bf->atlas_idx != 0 )
    {
        rhi()->unregister_texture( bf->atlas_idx );
        bf->atlas_idx = 0;
    }
    if ( rhi_handle_valid( bf->atlas ) )
    {
        rhi()->texture_destroy( bf->atlas );
        bf->atlas = ( rhi_texture_t ){ 0 };
    }
}

/* Expand a bit font (1 bpp) into a resident bmp atlas (R8), finalize the white/dash tail, and
   upload it. */
static bool
bmp_atlas_build( bmp_font_t* bf )
{
    const bit_font_def_t* def = bf->def;

    /* Atlas is uploaded taller than the glyph grid: font_finalize_atlas appends one white texel
       row plus GUI_DASH_PATTERN_COUNT stipple rows so solid fills and dashes sample the same
       atlas as text.  Glyph V coords divide by tex_h, so the appended rows never bleed in. */
    u32 tex_h = font_atlas_tex_h( def->atlas_h );

    /* Fixed-size pixel staging buffer; font_tool enforces the same limit at generation time.
       Sized to the largest built-in atlas (16x16 font: 256x128 atlas) plus the appended rows. */
    ORB_ASSERT( def->atlas_w * tex_h <= 256u * 256u );
    u8  pixels[ 256 * 256 ];
    memset( pixels, 0, def->atlas_w * tex_h );

    /* Expand each glyph's packed 1-bpp rows into opaque/transparent R8 texels. */
    for ( u32 g = 0; g < def->glyph_count; ++g )
    {
        u32 col = g % def->glyphs_row;
        u32 row = g / def->glyphs_row;
        u32 ox  = col * def->glyph_w;
        u32 oy  = row * def->glyph_h;

        for ( u32 r = 0; r < def->glyph_h; ++r )
        {
            /* Read one or two bytes per row depending on glyph width. */
            u32 off  = ( g * def->glyph_h + r ) * def->row_stride;
            u32 bits = def->data[ off ];
            if ( def->row_stride > 1 )
                bits |= (u32)def->data[ off + 1 ] << 8;

            for ( u32 c = 0; c < def->glyph_w; ++c )
            {
                u32 px = ox + c;
                u32 py = oy + r;
                pixels[ py * def->atlas_w + px ] = ( bits & ( 1u << c ) ) ? 0xFF : 0x00;
            }
        }
    }

    /* Append the white texel + dash rows and resolve the scale-free UV metrics. */
    font_finalize_atlas( pixels, def->atlas_w, def->atlas_h, tex_h, &bf->metrics );
    bf->tex_h = tex_h;

    bf->atlas = rhi()->texture_create( &( rhi_texture_desc_t ){
        .width        = def->atlas_w,
        .height       = tex_h,
        .depth        = 1,
        .mip_levels   = 1,
        .array_layers = 1,
        .format       = RHI_FORMAT_R8_UNORM,
        .usage        = RHI_TEXTURE_USAGE_SAMPLED | RHI_TEXTURE_USAGE_TRANSFER_DST,
        .memory       = RHI_MEMORY_GPU_ONLY,
        .debug_name   = def->debug_name,
    } );
    if ( !rhi_handle_valid( bf->atlas ) )
        return false;

    if ( !rhi()->upload_texture( bf->atlas, pixels, def->atlas_w * tex_h, 0, 0 ) )
    {
        rhi()->texture_destroy( bf->atlas );
        bf->atlas = ( rhi_texture_t ){ 0 };
        return false;
    }

    bf->atlas_idx = rhi()->register_texture( bf->atlas );
    if ( bf->atlas_idx == 0 )
    {
        rhi()->texture_destroy( bf->atlas );
        bf->atlas = ( rhi_texture_t ){ 0 };
        return false;
    }

    bmp_resolve_metrics( bf );               // complete the scale-dependent metrics + atlas_idx
    return true;
}

/*----------------------------------------------------------------------------------------------
    bmp_init / bmp_shutdown / bmp_atlas_bytes
----------------------------------------------------------------------------------------------*/

bool
bmp_init( void )
{
    bmp_show_sizes();

    /* bmp_atlas_destroy is safe on uninitialized fonts, so a failure here can be cleaned up by
       the caller's font_shutdown in a single path. */
    bool ok = true;
    for ( u32 i = 0; i < GUI_FONT_BITMAP_MAX; ++i )
        ok = ok && bmp_atlas_build( &s_bmps[ i ] );
    return ok;
}

void
bmp_shutdown( void )
{
    for ( u32 i = 0; i < GUI_FONT_BITMAP_MAX; ++i )
        bmp_atlas_destroy( &s_bmps[ i ] );
    s_bmp_active = NULL;
}

/* GPU bytes held by the resident bmp atlases (R8_UNORM, 1 byte/pixel). */
u32
bmp_atlas_bytes( void )
{
    u32 bytes = 0;
    for ( u32 i = 0; i < GUI_FONT_BITMAP_MAX; ++i )
    {
        const bmp_font_t* bf = &s_bmps[ i ];
        if ( rhi_handle_valid( bf->atlas ) )
            bytes += bf->def->atlas_w * bf->tex_h;   /* tex_h includes the appended rows */
    }
    return bytes;
}

/*----------------------------------------------------------------------------------------------
    bmp_glyph -- per-character draw parameters for a bmp slot (fixed-grid UV, monospace advance).
----------------------------------------------------------------------------------------------*/

void
bmp_glyph( const font_slot_t* slot, u8 ch,
           f32* u0, f32* v0, f32* u1, f32* v1,
           f32* ox, f32* oy, f32* gw, f32* gh, f32* advance )
{
    if ( ch < 32 || ch > 127 ) ch = (u8)'?';
    const bit_font_def_t* def = slot->bmp.def;
    const font_metrics_t* m   = &slot->metrics;

    u32 idx = (u32)( ch - 32 );
    u32 col = idx % def->glyphs_row;
    u32 row = idx / def->glyphs_row;

    /* V scales by 1/tex_h (the padded upload height), not the glyph-grid height, so the appended
       white row stays outside every glyph's UV range.  Both scales are precomputed per font
       (inv_atlas_w / inv_atlas_h), so this is multiplies, not per-glyph divides. */
    f32 iw = m->inv_atlas_w;
    f32 ih = m->inv_atlas_h;
    *u0 = (f32)( col * def->glyph_w ) * iw;
    *v0 = (f32)( row * def->glyph_h ) * ih;
    *u1 = *u0 + (f32)def->glyph_w     * iw;
    *v1 = *v0 + (f32)def->glyph_h     * ih;

    *ox      = 0.0f;
    *oy      = 0.0f;
    *gw      = m->char_w;
    *gh      = m->char_h;
    *advance = m->char_w;
}

// clang-format on
/*============================================================================================*/
