/*==============================================================================================

    engine_main.c

==============================================================================================*/

#include <stdio.h>    // printf, fprintf

#include "orb.h"              // general project settings and declarations
#include "module/module.h"    // module system (boot, load/unload, tick, shutdown)

/* specifiy before including headers */

#define BASE_LINK_STATIC    // static to exe and dynamic for modules if not declared
#define CORE_LINK_STATIC    // static to exe and dynamic for modules if not declared
#define JOBS_LINK_STATIC    // static to exe and dynamic for modules if not declared

/* Tier 1 host-service headers only — struct path, safe to call here. */

#include "core_api.h"
#include "sys/sys_api.h" /* change name? ew */
#include "engine_api.h"

/* Only exposed to host that initializes the static modules */
struct module_api_s* core_get_module_api( void );
struct module_api_s* sys_get_module_api( void );
struct module_api_s* engine_get_module_api( void );

/* Tier 2 headers included only so module_load() macro can resolve the getter names
   in BUILD_STATIC.  Their API functions are NOT called from main(). */
#include "runtime/modules/render/render_api.h"
#include "runtime/modules/audio/audio_api.h"

#ifdef BUILD_STATIC
struct module_api_s* audio_get_module_api( void );
struct module_api_s* render_get_module_api( void );
struct module_api_s* game_get_module_api( void );
struct module_api_s* sample_game_get_module_api( void );
#endif

/* Static lnked direct calls */
#include "sys/sys.h"

/*============================================================================================*/

static void
host_force_hot_reload( void )
{
    printf( "[host] force hot reload\n" );

    /*
        Later:
            module_sys_reload_changed_modules();
    */
}

static void
host_force_recompile( void )
{
    printf( "[host] force recompile\n" );

    /*
        Later:
            build_tool_compile_game_code();
    */
}

/*============================================================================================*/
/* test the module system by booting it, registering some static modules,
   loading some dynamic ones, and running a main loop */

void
module_test( void )
{
    /*------------------------------------------------------------------------------------------
        1. Boot
    ------------------------------------------------------------------------------------------*/

    module_system_init();

    /* ── Tier 1: Host services — explicit module_static_load, never a DLL ────────────── */

    if ( !module_static_load( "core", core_get_module_api() ) )
        goto shutdown;
    if ( !module_static_load( "sys", sys_get_module_api() ) )
        goto shutdown;
    if ( !module_static_load( "engine", engine_get_module_api() ) )
        goto shutdown;

    /* ── Tier 2: Switchable modules — static or DLL depending on BUILD_STATIC ─────── */

    if ( !module_load( render ) )
    {
        fprintf( stderr, "load renderer: %s\n", module_last_error() );
        goto shutdown;
    }
    if ( !module_load( audio ) )
    {
        fprintf( stderr, "load audio: %s\n", module_last_error() );
        goto shutdown;
    }
    if ( !module_load( game ) )
    {
        fprintf( stderr, "load game: %s\n", module_last_error() );
        goto shutdown;
    }
    if ( !module_load( sample_game ) )
    {
        fprintf( stderr, "load sample_game: %s\n", module_last_error() );
        goto shutdown;
    }


    /*------------------------------------------------------------------------------------------
        3. Initialize — topo-sort fires audio_init() before renderer_init()
    ------------------------------------------------------------------------------------------*/

    if ( module_init_all() == false )
    {
        fprintf( stderr, "fatal: %s\n", module_last_error() );
        goto shutdown;
    }

    module_list_all();

    core_api()->log( "Module System Initialized\n" );

    // core_api()->log( "startup complete  workers=%d", jobs_api()->worker_count() );

    /*------------------------------------------------------------------------------------------
        4. Application API usage.

            audio_api() and render_api() are generated by MODULE_DEFINE_ACCESS_FUNC in each _api.h.

            BUILD_STATIC:  audio_api() → &g_audio_api_struct    (direct, no indirection)
            dynamic:       audio_api() → g_audio_api_ptr        (one load, cached in init)

            The call site is identical.  The performance difference is at the compiler level,
            not in this source file.  This is the entire point of the pattern.
    ------------------------------------------------------------------------------------------*/

    /* ---- console input ----------------------------------------------- */

    {
        if ( !sys_console_input_init() )
        {
            printf( "[host] failed to initialize console input\n" );
            return;
        }
        printf( "\nBootstrap host running.\n" );
        printf( "Keys:\n" );
        printf( "  R = force hot reload\n" );
        printf( "  C = force recompile\n" );
        printf( "  Q = quit\n" );
        printf( "  ESC = quit\n" );
    }

    /* ---- game loop --------------------------------------------------- */

    const float dt      = 1.0f / 60.0f;

    bool        running = true;
    while ( running )
    {
        // engine->print( "Looping...\n" );
        // sys->tick_sleep( 100 );

        module_system_tick( dt ); /* tick all INITIALIZED modules        */

        /* Application-level API calls — no #ifdefs here, ever. */
        // render_api()->draw_frame( dt );
        // renderer_api()->draw_quad( 0.0f, 0.0f, 100.0f, 100.0f, 0xFF0000FF );
        // renderer_api()->draw_quad( 200.0f, 150.0f, 50.0f, 50.0f, 0x00FF00FF );
        // renderer_api()->end_frame();

        if ( 1 )
        {
            // engine_request_quit();
        }

        sys_console_input_poll();

        if ( sys_key_pressed( PLATFORM_KEY_R ) )
        {
            printf( "[host] R key pressed\n" );
            // hot_reload();
        }

        if ( sys_key_pressed( PLATFORM_KEY_C ) )
        {
            printf( "[host] C key pressed\n" );
            // recompile_code();
        }

        if ( sys_key_pressed( PLATFORM_KEY_Q ) )
        {
            printf( "[host] Q key pressed\n" );
            running = false;
        }

        module_check_reloads(); /* poll disk; reload any changed DLL   */
    }

    sys_console_input_shutdown();

    /* ------------------------------------------------------------------ */
    /* 6. Shutdown: exit in reverse dep order, unload DLLs, free state    */
    /* ------------------------------------------------------------------ */

shutdown:

    fprintf( stderr, "%s\n", module_last_error() );
    module_system_exit();
}

/*============================================================================================*/
/* main entry point */

void test( int argc, char** argv );    // <-- test entry point, defined in engine_test.c

int
main( int argc, char** argv )
{
    module_test();

    if ( 0 )
    {
        test( argc, argv );
    }

    return 0;
}

/*============================================================================================*/