/*==============================================================================================

    runtime_service/imgui/imgui_font_builtin.c -- Built-in bitmap font atlas data.

    Two hardcoded bitmap fonts serve as the compile-time fallback (no file required):
        8x8  -- compact atlas 128x64,  pixel-perfect at multiples of 8
        8x12 -- default atlas 128x128, pixel-perfect at multiples of 12

    Atlas layout (same formula for both):
        16 glyphs per row x glyph_w pixels = atlas_w pixels wide
        6 glyph rows      x glyph_h pixels = atlas_h pixels tall
    Glyph index for character ch (32-127): idx = ch - 32
        col = idx % 16,  row = idx / 16
    UV: u0 = col*glyph_w/atlas_w,  v0 = row*glyph_h/atlas_h

    Included by imgui.c before imgui_font.c.

==============================================================================================*/
// clang-format off

/*----------------------------------------------------------------------------------------------
    Types
----------------------------------------------------------------------------------------------*/

/* Pre-resolved metrics shared by both font sources; callers read from s_font. */
typedef struct
{
    f32  char_h;        // pixel height of the text area
    f32  line_h;        // total line advance
    f32  char_w;        // monospace advance (0 for proportional fonts)
    u32  atlas_idx;     // bindless texture index
    bool proportional;  // true = use per-glyph advance from lookup[]

} font_metrics_t;

static font_metrics_t* s_font = NULL;  // points to the active font's metrics

/* Compile-time description of one bitmap font. */
typedef struct
{
    u32             atlas_w;            // width of the font atlas in pixels
    u32             atlas_h;            // height of the font atlas in pixels
    u32             glyph_w;            // width of each glyph cell in pixels (including padding; 0 for whitespace)
    u32             glyph_h;            // height of each glyph cell in pixels (including padding)

    u32             glyphs_row;         // number of glyphs per row in the atlas (16 for our built-in fonts)
    u32             glyph_count;        // number of glyphs in the atlas (96 for our built-in fonts; 0 for whitespace-only)
    u32             row_stride;         // bytes per glyph row: 1 for 8-wide fonts (u8), 2 for 12/16-wide fonts (u16 LE)

    const u8*       data;
    const char*     debug_name;

} bitmap_font_def_t;

/* Runtime GPU resources for one bitmap font. */
typedef struct
{
    font_metrics_t              metrics;   // first: common resolved values (char_h, char_w, etc.)

    const bitmap_font_def_t*    def;
    rhi_texture_t               atlas;
    u32                         atlas_idx;

} bitmap_font_t;

/*==============================================================================================

    Font Tables (unity include data tables generated by font_tool)

    Good base design size (e.g., 8px, 12px, 16px, 24px, or 32px)
    https://www.dafont.com/bitmap.php

==============================================================================================*/

// GENERATED: bitmap font data (glyph bitmaps and metadata) for 8x8-16x16 pixel glyphs
#include "runtime_service/imgui/font/imgui_font_data.c"

//  C:\WINDOWS\FONTS\CONSOLA.TTF 24 consola_24.c
#include "runtime_service/imgui/font/consola_24.c"

// "F:\orb\font_source\ProggyTinyTTRegular.ttf" 24 proggy_tiny_24.c (renders smaler)
// "F:\orb\font_source\ProggyTinyTTRegular.ttf" 32 proggy_tiny_32.c (renders smaller)
#include "runtime_service/imgui/font/proggy_tiny_16.c"
#include "runtime_service/imgui/font/proggy_tiny_32.c"

// F:\orb\font_source\JetBrainsMonoNL-Bold.ttf 16 jetbrains_bold_16.c
// F:\orb\font_source\JetBrainsMonoNL-Bold.ttf 20 jetbrains_bold_20.c
// F:\orb\font_source\JetBrainsMonoNL-Bold.ttf 24 jetbrains_bold_24.c
#include "runtime_service/imgui/font/jetbrains_bold_16.c"
#include "runtime_service/imgui/font/jetbrains_bold_20.c"
#include "runtime_service/imgui/font/jetbrains_bold_24.c"

// "F:\orb\font_source\dogicapixelbold.ttf" 12 dogica_16.c
// #include "runtime_service/imgui/font/dogica_16.c"

/*----------------------------------------------------------------------------------------------
    GPU atlas instances
    
----------------------------------------------------------------------------------------------*/

/* One slot per imgui_font_t; designated initializers keep slot == enum value,
   so bitmap_font_select() and the init/shutdown loops can index directly. */
static bitmap_font_t s_bitmaps[ IMGUI_FONT_BITMAP_MAX ] = 
{
    // built-in fonts generated by AI
    [ IMGUI_FONT_BITMAP_8 ]           = { .def = &s_def_8 },
    [ IMGUI_FONT_BITMAP_16 ]          = { .def = &s_def_16 },
    [ IMGUI_FONT_BITMAP_12 ]          = { .def = &s_def_12 },

    // font_tool.exe generated
    [ IMGUI_FONT_BITMAP_16_PROGGY]    = { .def = &s_def_proggy_tiny_16 },
    [ IMGUI_FONT_BITMAP_20_PROGGY]    = { .def = &s_def_proggy_tiny_20 },

    [ IMGUI_FONT_BITMAP_16_JETBOLD]   = { .def = &s_def_jetbrains_bold_22 }, // fixed
    [ IMGUI_FONT_BITMAP_20_JETBOLD]   = { .def = &s_def_jetbrains_bold_27 }, // fixed 
    [ IMGUI_FONT_BITMAP_24_JETBOLD ]  = { .def = &s_def_jetbrains_bold_33 }, // fixed

    [ IMGUI_FONT_BITMAP_24_CONSOLA ]  = { .def = &s_def_consola_24 },        
};

static void bitmap_show_sizes()
{

    printf( "bitmap fonts in memory:..\n" );
    for ( int i = 0; i < IMGUI_FONT_BITMAP_MAX; ++i )
    {
        const bitmap_font_def_t* def = s_bitmaps[ i ].def;
        
        printf( "%-32s: [%d] %-3dx%3d atlas, w:%2d h:%2d, %2d glyphs per row, row stride %2d\n",
            def->debug_name, i, def->atlas_w, def->atlas_h, def->glyph_w, def->glyph_h, def->glyphs_row, def->row_stride );
    }

    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_8",          sizeof( s_font8_data ));
    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_16",         sizeof( s_font16_data ));
    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_12",         sizeof( s_font12_data ));
    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_16_PROGGY",  sizeof( s_font_proggy_tiny_16_data ));
    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_20_PROGGY",  sizeof( s_font_proggy_tiny_20_data ));

    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_16_JETBOLD", sizeof( s_font_jetbrains_bold_22_data ));
    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_20_JETBOLD", sizeof( s_font_jetbrains_bold_27_data  ));
    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_24_JETBOLD", sizeof( s_font_jetbrains_bold_33_data  ));

    printf( "%-32s: %zu bytes\n", "IMGUI_FONT_BITMAP_24_CONSOLA", sizeof( s_font_consola_24_data  ));

    printf( "\n" );

}

static bitmap_font_t*   s_bitmap_active     = NULL;
static imgui_font_t     s_bmp_font          = IMGUI_FONT_BITMAP_16;
static u32              s_bmp_scale         = 1;

static void
bitmap_font_select( imgui_font_t font )
{
    /* Out-of-range requests fall back to the default 8x12 atlas. */
    if ( (u32)font >= IMGUI_FONT_BITMAP_MAX )
        font = IMGUI_FONT_BITMAP_12;

    s_bmp_font      = font;
    s_bitmap_active = &s_bitmaps[ font ];

    /* Resolve metrics from native pixel dimensions scaled by s_bmp_scale.
       All downstream code (widget sizing, glyph quads, text width) reads from s_font,
       so the scale is transparent -- callers see it as if the font were natively that size. */

    const bitmap_font_def_t* def = s_bitmap_active->def;
    f32 s = (f32)s_bmp_scale;
    s_bitmap_active->metrics = ( font_metrics_t ){
        .char_h       = (f32)( def->glyph_h * s ),
        .line_h       = (f32)( def->glyph_h + def->glyph_h / 4u ) * s,
        .char_w       = (f32)( def->glyph_w * s ),
        .atlas_idx    = s_bitmap_active->atlas_idx,
        .proportional = false,
    };
    s_font = &s_bitmap_active->metrics;
}

static void
bitmap_scale_set( u32 scale )
{
    s_bmp_scale = ( scale < 1u ) ? 1u : scale;
    if ( s_bitmap_active )
        bitmap_font_select( s_bmp_font );   // reapply metrics with new scale
}

/*----------------------------------------------------------------------------------------------
    bitmap_atlas_shutdown / bitmap_atlas_init
----------------------------------------------------------------------------------------------*/

static void
bitmap_atlas_shutdown( bitmap_font_t* bf )
{
    if ( bf->atlas_idx != 0 )
    {
        rhi()->unregister_texture( bf->atlas_idx );
        bf->atlas_idx = 0;
    }
    if ( rhi_handle_valid( bf->atlas ) )
    {
        rhi()->texture_destroy( bf->atlas );
        bf->atlas = ( rhi_texture_t ){ 0 };
    }
}

static bool
bitmap_atlas_init( bitmap_font_t* bf )
{
    const bitmap_font_def_t* def = bf->def;

    /* Fixed-size pixel staging buffer; font_tool enforces the same limit at generation time.
       Sized to the largest built-in atlas (16x16 font: 256x128 atlas) */
    ORB_ASSERT( def->atlas_w * def->atlas_h <= 256u * 256u );
    u8  pixels[ 256 * 256 ];
    memset( pixels, 0, def->atlas_w * def->atlas_h );

    for ( u32 g = 0; g < def->glyph_count; ++g )
    {
        u32 col = g % def->glyphs_row;
        u32 row = g / def->glyphs_row;
        u32 ox  = col * def->glyph_w;
        u32 oy  = row * def->glyph_h;

        for ( u32 r = 0; r < def->glyph_h; ++r )
        {
            /* Read one or two bytes per row depending on glyph width. */
            u32 off  = ( g * def->glyph_h + r ) * def->row_stride;
            u32 bits = def->data[ off ];
            if ( def->row_stride > 1 )
                bits |= (u32)def->data[ off + 1 ] << 8;

            for ( u32 c = 0; c < def->glyph_w; ++c )
            {
                u32 px = ox + c;
                u32 py = oy + r;
                pixels[ py * def->atlas_w + px ] = ( bits & ( 1u << c ) ) ? 0xFF : 0x00;
            }
        }
    }

    bf->atlas = rhi()->texture_create( &( rhi_texture_desc_t ){
        .width        = def->atlas_w,
        .height       = def->atlas_h,
        .depth        = 1,
        .mip_levels   = 1,
        .array_layers = 1,
        .format       = RHI_FORMAT_R8_UNORM,
        .usage        = RHI_TEXTURE_USAGE_SAMPLED | RHI_TEXTURE_USAGE_TRANSFER_DST,
        .memory       = RHI_MEMORY_GPU_ONLY,
        .debug_name   = def->debug_name,
    } );
    if ( !rhi_handle_valid( bf->atlas ) )
        return false;

    if ( !rhi()->upload_texture( bf->atlas, pixels, def->atlas_w * def->atlas_h, 0, 0 ) )
    {
        rhi()->texture_destroy( bf->atlas );
        bf->atlas = ( rhi_texture_t ){ 0 };
        return false;
    }

    bf->atlas_idx = rhi()->register_texture( bf->atlas );
    if ( bf->atlas_idx == 0 )
    {
        rhi()->texture_destroy( bf->atlas );
        bf->atlas = ( rhi_texture_t ){ 0 };
        return false;
    }

    return true;
}

// clang-format on
/*============================================================================================*/
