/* Generated by reflect_tool -- do not edit. */

#include "orb.h"
#include "engine/ref/ref_import.h"
#include "-out.generated.h"

/*==============================================================================================
    Reflection Registration
==============================================================================================*/

void
-out_ref_register( const ref_reg_api_t* api )
{
    UNUSED( api );
}
