#ifndef _OUT_GENERATED_H
#define _OUT_GENERATED_H
/* Generated by reflect_tool -- do not edit. */

#include "engine/ref/ref_import.h"

void -out_ref_register( const ref_reg_api_t* api );

#endif /* _OUT_GENERATED_H */
