/*==============================================================================================

    rs_gen_output.c - write <module>.generated.h and <module>.generated.c

    Phase 1: emits empty-but-valid stubs. The register function body will be
    populated once the parser produces full type/field/enum data.

==============================================================================================*/

#include "rs_gen_internal.h"

/*----------------------------------------------------------------------------------------------
    Internal helpers
----------------------------------------------------------------------------------------------*/

static void
to_upper_guard( char* dst, const char* src, int max )
{
    int i = 0;
    for ( ; i < max - 1 && src[ i ]; i++ )
    {
        char c = src[ i ];
        if ( c >= 'a' && c <= 'z' )
            c = (char)( c - 32 );
        else if ( c == '.' || c == '-' || c == '/' || c == '\\' )
            c = '_';
        dst[ i ] = c;
    }
    dst[ i ] = '\0';
}

/*----------------------------------------------------------------------------------------------
    Public
----------------------------------------------------------------------------------------------*/

int
rg_output( const char* output_dir, const char* module_name, const rg_parse_data_t* data )
{
    char h_path[ RG_MAX_PATH ];
    char c_path[ RG_MAX_PATH ];
    char guard[ RG_MAX_NAME ];

    // Build output paths
    rg_str_copy( h_path, output_dir, RG_MAX_PATH );
    rg_str_cat( h_path, "/", RG_MAX_PATH );
    rg_str_cat( h_path, module_name, RG_MAX_PATH );
    rg_str_cat( h_path, ".generated.h", RG_MAX_PATH );

    rg_str_copy( c_path, output_dir, RG_MAX_PATH );
    rg_str_cat( c_path, "/", RG_MAX_PATH );
    rg_str_cat( c_path, module_name, RG_MAX_PATH );
    rg_str_cat( c_path, ".generated.c", RG_MAX_PATH );

    // Build include guard: MODULE_NAME_GENERATED_H
    to_upper_guard( guard, module_name, RG_MAX_NAME );
    rg_str_cat( guard, "_GENERATED_H", RG_MAX_NAME );

    // Write header
    FILE* fh = fopen( h_path, "w" );
    if ( !fh )
    {
        fprintf( stderr, "[build_reflect] error: cannot write %s\n", h_path );
        return 0;
    }
    fprintf( fh, "#ifndef %s\n", guard );
    fprintf( fh, "#define %s\n", guard );
    fprintf( fh, "// Generated by build_reflect -- do not edit\n\n" );
    fprintf( fh, "#include \"engine/core/reflect/rs.h\"\n\n" );
    fprintf( fh, "void %s_reflect_register( uint16_t frame_id );\n\n", module_name );
    fprintf( fh, "#endif // %s\n", guard );
    fclose( fh );

    // Write implementation
    FILE* fc = fopen( c_path, "w" );
    if ( !fc )
    {
        fprintf( stderr, "[build_reflect] error: cannot write %s\n", c_path );
        return 0;
    }
    fprintf( fc, "// Generated by build_reflect -- do not edit\n\n" );
    fprintf( fc, "#include \"%s.generated.h\"\n\n", module_name );
    fprintf( fc, "void %s_reflect_register( uint16_t frame_id )\n", module_name );
    fprintf( fc, "{\n" );
    fprintf( fc, "    (void)frame_id;\n" );
    fprintf( fc, "    // build_reflect: %d type(s), %d enum(s) -- implementation pending\n",
             data->type_count, data->enum_count );
    fprintf( fc, "}\n" );
    fclose( fc );

    return 1;
}
